import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './ui/Navbar/Navbar'
import { poppins } from './ui/fonts'
import PrelineScript from "./components/PrelineScript";
import Footer from './ui/Footer/Footer'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      
      <body className={`${poppins.className} bg-purple-50`} >
      <ToastContainer />
        <Navbar />
          {children}
        <Footer/>
      </body>
      <PrelineScript />
      <script type="text/javascript" id="hs-script-loader" async defer src="//js-eu1.hs-scripts.com/26707346.js"></script>
    </html>
    
  )
}
